#!/bin/sh
# Simple While Loop Example

# This script demonstrates a simple while loop in shell scripting. It continuously prompts the user 
# to enter a choice, offering options to exit the loop or continue to the next iteration based on 
# the user's input.

# 🛠️ Usage:
# Make sure the script has executable permissions. Run it using ./script_name.sh from the terminal.

while true
do
  echo "Entering while loop ..."
  echo "Choose 1 to exit loop."
  echo "Choose 2 to go to top of loop."
  echo -n "Enter choice: "
  read choice
  
  if test $choice = 1
  then
    break
  fi
  
  echo "Bypassing break."
  
  if test $choice = 2
  then
     continue
  fi
  
  echo "Bypassing continue."
done

echo "Exit while loop."
