#!/bin/sh
# Check if a file is executable.

# This script checks if a specified file exists and if it is executable.
# It uses the 'test' command to check both existence (-e) and executable permissions (-x) of the file.
# Depending on the result, it prints whether the file is executable, does not exist, or is not executable.

# 🛠️ Usage:
# Make sure the script has executable permissions. Run it using ./script_name.sh <file_name>

# Better version!
if test -e $1 && test -x $1
then
   echo File $1 is executable.
elif test ! -e $1
then
   echo File $1 does not exist.
else
   echo File $1 is not executable.
fi
